"""Produce a single-file markdown report of predicted vs. actual 2026-Q1
questions per analyst, with the judge's verdict for each pairing."""

from __future__ import annotations

import json
import os
import glob


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main() -> None:
    test = json.load(open(os.path.join(ROOT, "data", "analysts_test.json")))
    actuals = test["per_analyst_actual_questions"]

    lines: list[str] = []
    lines.append("# Predicted vs Actual: RCL 2026-Q1\n")
    lines.append(
        "Generated by `src/run_pipeline.py` against `gpt-5-mini`. "
        "Personas built from 16 prior calls (2022-Q1 through 2025-Q4) using "
        "the analyst BDE schema "
        "(`coverage_profile` / `reasoning_style` / `recurring_concerns`). "
        "Match levels assigned by an LLM judge given the predicted question "
        "set and the actual question(s).\n"
    )

    # Aggregate stats first
    score_files = sorted(glob.glob(os.path.join(ROOT, "data", "scores", "*.json")))
    n_actual = n_exact = n_partial = n_miss = 0
    rows: list[tuple[str, dict]] = []
    for sf in score_files:
        sc = json.load(open(sf))
        name = os.path.basename(sf).replace(".json", "").replace("_", " ")
        rows.append((name, sc))
        s = sc.get("summary", {})
        n_actual += s.get("n_actual", 0)
        n_exact += s.get("n_exact", 0)
        n_partial += s.get("n_partial", 0)
        n_miss += s.get("n_miss", 0)

    hit_rate = (n_exact + n_partial) / n_actual if n_actual else 0.0
    lines.append("## Aggregate\n")
    lines.append(f"- Analysts scored: **{len(rows)}** (returning analysts with ≥1 prior question)")
    lines.append(f"- Actual questions: **{n_actual}**")
    lines.append(f"- Exact matches: **{n_exact}**")
    lines.append(f"- Partial matches: **{n_partial}**")
    lines.append(f"- Misses: **{n_miss}**")
    lines.append(f"- Hit rate (exact or partial): **{hit_rate:.1%}**\n")

    # Per-analyst summary table
    lines.append("| Analyst | n_prior | actual | exact | partial | miss | hit |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    analysts = json.load(open(os.path.join(ROOT, "data", "analysts.json")))
    for name, sc in rows:
        s = sc.get("summary", {})
        n_prior = analysts.get(name, {}).get("n_questions", 0)
        hit = s.get("hit_rate_exact_or_partial", 0.0)
        lines.append(
            f"| {name} | {n_prior} | {s.get('n_actual', 0)} | "
            f"{s.get('n_exact', 0)} | {s.get('n_partial', 0)} | "
            f"{s.get('n_miss', 0)} | {hit:.0%} |"
        )
    lines.append("")

    # Detailed per-analyst sections
    for name, sc in rows:
        underscored = name.replace(" ", "_")
        pred = json.load(open(os.path.join(ROOT, "data", "predictions", f"{underscored}.json")))
        lines.append(f"\n## {name.title()}\n")

        n_prior = analysts.get(name, {}).get("n_questions", 0)
        n_calls = analysts.get(name, {}).get("n_calls", 0)
        lines.append(f"*Training history: {n_prior} questions across {n_calls} calls.*\n")

        lines.append("**Actual question(s) on 2026-Q1:**\n")
        for a in actuals.get(name, []):
            lines.append("> " + a["question"].strip().replace("\n", "\n> "))
            lines.append("")

        lines.append("**Predicted questions:**\n")
        for i, p in enumerate(pred.get("predicted_questions", [])):
            lines.append(
                f"- *[{p.get('topic_label', '?')}]* {p.get('question_text', '').strip()}"
            )
        lines.append("")

        lines.append("**Judge verdicts:**\n")
        for s in sc.get("scored", []):
            lines.append(
                f"- **{s.get('match_level', '?').upper()}** "
                f"(actual_topic = `{s.get('actual_topic', '?')}`, "
                f"best_pred_idx = {s.get('best_predicted_index')})  \n  "
                f"_reasoning:_ {s.get('reasoning', '')}"
            )
        lines.append("")

    out = "\n".join(lines)
    out_path = os.path.join(ROOT, "data", "predicted_vs_actual_report.md")
    with open(out_path, "w") as f:
        f.write(out)
    print(f"Wrote {out_path} ({len(out)} chars)")


if __name__ == "__main__":
    main()
